# Site
repository: dbeusink/dbeusink.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daan Beusink
title: C# Software Developer
email: daan@beus.ink
website: www.beus.ink

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  dbeusink
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: daanbeusink
linkedin_username: dbeusink
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
- title: KVK 93728980
  icon: fas fa-stamp
  url: https://www.kvk.nl/bestellen/#/93728980000059251050

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  👨‍💻 Welcome to my digital domain! I'm Daan, a coding enthusiast dedicated to crafting digital solutions that power industrial innovation. 🚀

  In my previous role, I specialized in Programmable Logic Controllers (PLCs), creating precise routines for machines. Today, I leverage my expertise in C# to develop software that optimizes warehouse and distribution operations. 📦

  At FORTNA, I apply logic and creativity to build applications that enhance productivity in warehouses. 🛠️ My code is more than just lines; it drives the efficiency of conveyor belts, automates processes, and streamlines operations.

  Beyond my work, I'm a people-person with a passion for exploring the world. ✈️ Whether I'm traveling or solving complex problems, I'm fully engaged and eager to learn.

  Join me on this digital journey as we explore the realms of code, innovation, and technology. Let's collaborate and create something remarkable together! 🌟

  <mark>ChatGPT-3.5</mark>
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FORTNA (formerly Material Handling Systems Inc.)
        link: fortna.com
        # link_text: boringcompany.com
        sub_title: C# Software Engineer
        caption: August 2021 - present
        description: | # this will include new lines to allow paragraphs
            As a skilled C# software developer at FORTNA, I specialize in crafting advanced Warehouse Management System (WMS) solutions tailored to the dynamic needs of the warehouse, distribution, and parcel sectors. Through innovative coding and intricate problem-solving, I am dedicated to optimizing operations and enhancing efficiency. My role encompasses the design, development, and implementation of cutting-edge software that powers seamless logistics and elevates the industry standard.
            
            <mark>C#</mark> <mark>.NET</mark> <mark>WPF</mark> <mark>SQL</mark> <mark>ASP.NET Core</mark> <mark>Blazor</mark>
      - layout: left
        title: Westover
        link: westover.nl
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: March 2019 - August 2021
        description: | # this will include new lines to allow paragraphs
            I am a seasoned professional at Westover, excelling in C# software development and holding senior expertise in PLC programming. In this capacity, I specialize in crafting sophisticated Warehouse Management System (WMS) software solutions and industrial PLC programs, catering to a diverse range of clients. Through a blend of advanced coding and extensive automation knowledge, I am dedicated to delivering high-impact solutions that redefine efficiency and operational excellence across multiple industries.
            
            <mark>C#</mark> <mark>.NET</mark> <mark>WPF</mark> <mark>SQL</mark> <mark>Siemens</mark> <mark>Beckhoff</mark> <mark>Sigmatek</mark>
      - layout: left
        title: VanRiet Material Handling Systems
        link: vanrietgroup.com
        # link_text: boringcompany.com
        sub_title: PLC Software Engineer
        caption: October 2015 - March 2019
        description: | # this will include new lines to allow paragraphs
            As a dedicated PLC Software Engineer at VanRiet Material Handling Systems, my focus lies in crafting intricate software solutions tailored to industrial sorting systems. With precision and expertise, I develop and optimize PLC programs that drive the seamless functioning of these systems, contributing to enhanced efficiency and accuracy in material handling operations. Through a combination of technical prowess and a deep understanding of automation, I am committed to delivering software that powers the next level of innovation in modern manufacturing and logistics.
            
            <mark>Siemens S7 (S7-300, S7-400)</mark> <mark>Siemens TIA Portal (S7-1500)</mark> <mark>VBA</mark> <mark>C#</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HU University of Applied Sciences Utrecht
        caption: 2011 - 2015
        sub_title: Industrial Automation

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Join me in advancing the industrial landscape through innovative software solutions that bridge the gap between cutting-edge technology and operational excellence. Let's collaborate to transform challenges into opportunities and propel industries into a new era of efficiency and advancement.
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
